
platform :ios, '9.0'
xcodeproj 'BraintriTest.xcodeproj'

target 'BraintriTest' do
use_frameworks!

pod 'PureLayout'
pod 'Alamofire'
pod 'CodableAlamofire'
pod 'ReachabilitySwift'
pod 'Atributika'

end
